# Generated by Django 5.0.6 on 2026-06-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='area_interes',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='candidato',
            name='dui',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='candidato',
            name='estudios',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidato',
            name='habilidades',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='empresa',
            name='persona_contacto',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sector',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
