# Generated by Django 5.0.6 on 2026-06-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0002_candidato_area_interes_candidato_dui_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacante',
            name='experiencia',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vacante',
            name='numero_vacantes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vacante',
            name='tipo_contrato',
            field=models.CharField(choices=[('TIEMPO_COMPLETO', 'Tiempo Completo'), ('MEDIO_TIEMPO', 'Medio Tiempo'), ('TEMPORAL', 'Temporal'), ('PRACTICAS', 'Prácticas'), ('PROYECTO', 'Por Proyecto')], default='TIEMPO_COMPLETO', max_length=20),
        ),
    ]
