# Generated by Django 5.0.6 on 2026-06-03 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0003_vacante_experiencia_vacante_numero_vacantes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vacante',
            name='creado_por_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacantes_creadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
