# Generated by Django 5.0.6 on 2026-06-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0004_vacante_creado_por_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacante',
            name='nivel_experiencia',
            field=models.CharField(choices=[('SIN_EXPERIENCIA', 'Sin experiencia'), ('JUNIOR', 'Junior (1-2 años)'), ('MID_LEVEL', 'Mid-Level (3-5 años)'), ('SENIOR', 'Senior (5-8 años)'), ('EXPERT', 'Expert (+8 años)')], default='SIN_EXPERIENCIA', max_length=20),
        ),
    ]
