# Generated by Django 5.0.6 on 2026-06-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0005_vacante_nivel_experiencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En Revisión'), ('PRESELECCION', 'Preselección'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
    ]
