# Generated by Django 5.0.6 on 2026-06-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0007_candidato_categorias_interes_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En Revisión'), ('PRESELECCION', 'Preselección'), ('CONTRATADO', 'Contratado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
    ]
